name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          cd chatapp-backend    # đường dẫn dự án trên EC2
          git reset --hard               # Hủy mọi thay đổi local
          git clean -fd
          git pull origin main             # kéo code mới nhất từ GitHub
          npm install
          npm run build
          pm2 restart chatapp-backend  # Khởi động lại ứng dụng với PM2